/* T10b: build the compressed-pak blob + map the shim streams from.
 * usage: pack_paks <senkosp.dat> <outdir>
 * emits: <outdir>/lz4paks.bin, lz4pak_map.h, lz4pak_map.json
 *
 * Reads the RAW .dat -- valid because no texpatch record intersects any
 * packed pak (make_gdi.py --lz4 re-asserts this against the live manifest
 * on every build, so a future texpatch config trips loud, not silent).
 *
 * Mastering rules (spec §On-disc format, amended 2026-09-23 -- execution
 * ruling e618190: the original backward-only margin pass demoted every
 * chunk, data-independently; see docs/superpowers/plans and specs dated
 * 2026-09-23):
 *  - 64 KB chunks, LZ4-HC level 9, each padded to a 32-byte multiple.
 *  - Chunk demoted to STORED (raw bytes) when compression does not pay
 *    (align32(csize) >= usize).
 *  - Backward classification pass: the innermost kept-LZ4 chunk is
 *    flagged BOUNCE (decodes via the T3 ring -- disjoint output, no
 *    in-place margin needed) and seeds slack for every earlier chunk;
 *    earlier LZ4 chunks are demoted to STORED when the accumulated
 *    slack from kept chunks after them is short of
 *    pad + (csize >> 8) + 32 (lz4.h LZ4_DECOMPRESS_INPLACE_MARGIN).
 *  - Round-trip verify + layout re-check through the REAL lz4pak_lay.
 * Build failure here is build-fatal by design (gate 1). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lz4.h"
#include "lz4hc.h"
#include "lz4_lay.h"
#include "shim_iface.h"

unsigned int shim_crc32(const void *p, unsigned len);   /* shims/src/gd.c (HOST_TEST) */

static const struct { unsigned off, len; } PAKS[] = {
    { 0x0935a800u, 0x007e7800u },   /* window B: 2p-stages whole-pak tuple */
};
#define NPAK (sizeof PAKS / sizeof PAKS[0])
#define MAXCHUNK 128

static unsigned a32(unsigned c) { return (c + 31u) & ~31u; }

int main(int argc, char **argv) {
    if (argc != 3) { fprintf(stderr, "usage: pack_paks senkosp.dat outdir\n"); return 2; }
    FILE *in = fopen(argv[1], "rb");
    if (!in) { perror(argv[1]); return 1; }
    char path[512];
    snprintf(path, sizeof path, "%s/lz4paks.bin", argv[2]);
    FILE *fb = fopen(path, "wb");
    snprintf(path, sizeof path, "%s/lz4pak_map.h", argv[2]);
    FILE *fh = fopen(path, "w");
    snprintf(path, sizeof path, "%s/lz4pak_map.json", argv[2]);
    FILE *fj = fopen(path, "w");
    if (!fb || !fh || !fj) { perror("outdir"); return 1; }

    fprintf(fh, "/* GENERATED by tools/lz4pak/pack_paks -- do not edit.\n"
                " * Data tables for lz4_lay.h's types; included by gd_lz4.inc.c. */\n");
    fprintf(fj, "[");
    unsigned blob_fad = BLOB_FAD, total_blob = 0;

    for (unsigned p = 0; p < NPAK; p++) {
        unsigned ulen = PAKS[p].len;
        unsigned n = (ulen + LZ4PAK_CHUNK - 1) / LZ4PAK_CHUNK;
        if (n > MAXCHUNK) { fprintf(stderr, "pak %u: %u chunks > %d\n", p, n, MAXCHUNK); return 1; }
        unsigned char *plain = malloc(ulen);
        static unsigned char comp[MAXCHUNK][LZ4PAK_CHUNK + LZ4PAK_CHUNK / 16];
        static unsigned char back[LZ4PAK_CHUNK];
        static unsigned csize[MAXCHUNK], stored[MAXCHUNK], crc[MAXCHUNK];
        static unsigned bounce[MAXCHUNK];
        if (fseek(in, PAKS[p].off, SEEK_SET) || fread(plain, 1, ulen, in) != ulen) {
            fprintf(stderr, "pak %u: read fail @0x%x\n", p, PAKS[p].off); return 1;
        }
        /* compress + primary demotion (compression must pay) */
        for (unsigned i = 0; i < n; i++) {
            unsigned u = ulen - i * LZ4PAK_CHUNK;
            if (u > LZ4PAK_CHUNK) u = LZ4PAK_CHUNK;
            if (u % 32) { fprintf(stderr, "pak %u: tail %u not 32-mult\n", p, u); return 1; }
            int c = LZ4_compress_HC((char *)plain + i * LZ4PAK_CHUNK,
                                    (char *)comp[i], (int)u, sizeof comp[i], 9);
            stored[i] = (c <= 0 || a32((unsigned)c) >= u);
            csize[i] = stored[i] ? u : (unsigned)c;
            if (stored[i]) memcpy(comp[i], plain + i * LZ4PAK_CHUNK, u);
            crc[i] = shim_crc32(plain + i * LZ4PAK_CHUNK, u);
        }
        /* classification, backward sweep (spec §On-disc format, amended
         * 2026-09-23): the innermost kept-LZ4 chunk is BOUNCED (ring
         * decode, output disjoint -- no in-place margin); earlier LZ4
         * chunks need slack >= pad + (c>>8) + 32 from kept chunks after
         * them; incompressibles were already stored above. */
        unsigned long long slack = 0; int seen_lz4 = 0;
        for (int i = (int)n - 1; i >= 0; i--) {
            unsigned u = ulen - (unsigned)i * LZ4PAK_CHUNK;
            if (u > LZ4PAK_CHUNK) u = LZ4PAK_CHUNK;
            if (!stored[i]) {
                if (!seen_lz4) { bounce[i] = 1; seen_lz4 = 1; }
                else if (slack < (unsigned long long)(a32(csize[i]) - csize[i])
                                 + (csize[i] >> 8) + 32u) {
                    stored[i] = 1; csize[i] = u; bounce[i] = 0;
                    memcpy(comp[i], plain + (unsigned)i * LZ4PAK_CHUNK, u);
                }
            }
            slack += u - a32(csize[i]);
        }
        if (!seen_lz4) { fprintf(stderr, "pak %u: nothing compressible -- "
                                 "remove it from PAKS[]\n", p); return 1; }
        /* round-trip verify every chunk */
        unsigned S = 0, nstored = 0;
        for (unsigned i = 0; i < n; i++) {
            unsigned u = ulen - i * LZ4PAK_CHUNK;
            if (u > LZ4PAK_CHUNK) u = LZ4PAK_CHUNK;
            if (stored[i]) { nstored++;
                if (memcmp(comp[i], plain + i * LZ4PAK_CHUNK, u)) {
                    fprintf(stderr, "pak %u chunk %u: stored mismatch\n", p, i); return 1; }
            } else if (LZ4_decompress_safe((char *)comp[i], (char *)back,
                                           (int)csize[i], (int)u) != (int)u
                       || memcmp(back, plain + i * LZ4PAK_CHUNK, u)) {
                fprintf(stderr, "pak %u chunk %u: ROUND-TRIP FAIL\n", p, i); return 1;
            }
            S += a32(csize[i]);
        }
        unsigned R = (S + 2047u) & ~2047u, front = R - S;
        /* re-check through the REAL layout math the shim will run */
        struct lz4pak_chunk ch[MAXCHUNK];
        unsigned bounce_idx = (unsigned)-1;
        for (unsigned i = 0; i < n; i++) {
            ch[i].csize_flags = csize[i] | (stored[i] ? LZ4PAK_STORED : 0)
                                          | (bounce[i] ? LZ4PAK_BOUNCE : 0);
            ch[i].crc32 = crc[i];
            if (bounce[i]) bounce_idx = i;
        }
        struct lz4pak_entry e = { PAKS[p].off, ulen, blob_fad, R, front, n, ch };
        struct lz4_lay L;
        unsigned base_off = ulen - R;   /* dest offset of the DMA/blob window */
        for (unsigned i = 0; i < n; i++) {
            if (lz4pak_lay(&e, i, &L) || L.csize != csize[i] || L.stored != stored[i]
                || L.bounced != bounce[i]) {
                fprintf(stderr, "pak %u chunk %u: lay mismatch\n", p, i); return 1; }
            if (L.out_off + L.usize > base_off + L.lend_target) {
                fprintf(stderr, "pak %u chunk %u: INVARIANT FAIL\n", p, i); return 1; }
            /* fix-loop finding 2(a): the lay re-check above only proves
             * slack >= 0 (weaker) -- prove the REAL LZ4 in-place margin
             * for every non-bounced kept-LZ4 chunk (lz4.h
             * LZ4_DECOMPRESS_INPLACE_MARGIN: dst needs (csize>>8)+32
             * bytes of headroom past where unconsumed input starts). */
            if (!L.stored && !L.bounced) {
                unsigned long long have = (unsigned long long)base_off + L.in_off + L.csize;
                unsigned long long need = (unsigned long long)L.out_off + L.usize
                                         + (L.csize >> 8) + 32u;
                if (have < need) {
                    fprintf(stderr, "pak %u chunk %u: MARGIN FAIL (have=%llu need=%llu)\n",
                            p, i, have, need); return 1;
                }
            }
        }
        /* fix-loop finding 2(b): control test -- simulate the REAL in-place
         * decode once on the host instead of round-tripping each chunk in
         * isolation into scratch (that only proves the compressor works;
         * this proves the mastering). Lay the padded stream right-
         * justified exactly like the blob/DMA would, then decode chunk by
         * chunk IN PLACE in delivery order: stored = forward copy,
         * bounced = via a 64 KB scratch (reuses `back`, standing in for
         * the T3 ring) then copied in, kept-LZ4 = true in-place
         * LZ4_decompress_safe (src and dst alias the same buffer). A sign
         * error in the classification sweep would corrupt an unconsumed
         * chunk here even if the isolated round-trip above passed. */
        {
            unsigned char *sim = malloc(ulen);
            if (!sim) { perror("malloc sim"); return 1; }
            for (unsigned i = 0; i < n; i++) {
                lz4pak_lay(&e, i, &L);
                unsigned in_abs = base_off + L.in_off;
                memcpy(sim + in_abs, comp[i], L.csize);
                memset(sim + in_abs + L.csize, 0, a32(L.csize) - L.csize);
            }
            for (unsigned i = 0; i < n; i++) {
                lz4pak_lay(&e, i, &L);
                unsigned in_abs = base_off + L.in_off;
                if (L.stored) {
                    memmove(sim + L.out_off, sim + in_abs, L.usize);
                } else if (L.bounced) {
                    if (LZ4_decompress_safe((char *)sim + in_abs, (char *)back,
                                            (int)L.csize, (int)L.usize) != (int)L.usize) {
                        fprintf(stderr, "pak %u chunk %u: SIM BOUNCE FAIL\n", p, i);
                        free(sim); return 1;
                    }
                    memcpy(sim + L.out_off, back, L.usize);
                } else if (LZ4_decompress_safe((char *)sim + in_abs, (char *)sim + L.out_off,
                                               (int)L.csize, (int)L.usize) != (int)L.usize) {
                    fprintf(stderr, "pak %u chunk %u: SIM IN-PLACE FAIL\n", p, i);
                    free(sim); return 1;
                }
            }
            if (memcmp(sim, plain, ulen)) {
                fprintf(stderr, "pak %u: IN-PLACE SIM MISMATCH\n", p);
                free(sim); return 1;
            }
            free(sim);
        }
        printf("pak %u: IN-PLACE SIM PASS\n", p);
        /* emit blob: front pad, then each chunk zero-padded to a32 */
        static const unsigned char zero[2048];
        fwrite(zero, 1, front, fb);
        for (unsigned i = 0; i < n; i++) {
            fwrite(comp[i], 1, csize[i], fb);
            fwrite(zero, 1, a32(csize[i]) - csize[i], fb);
        }
        /* emit map tables */
        fprintf(fh, "static const struct lz4pak_chunk lz4pak_chunks%u[%u] = {\n", p, n);
        for (unsigned i = 0; i < n; i++)
            fprintf(fh, "    { 0x%08xu, 0x%08xu },\n", ch[i].csize_flags, ch[i].crc32);
        fprintf(fh, "};\n");
        fprintf(fj, "%s{\"cart_off\": %u, \"ulen\": %u, \"blob_fad\": %u, \"r_bytes\": %u}",
                p ? ", " : "", PAKS[p].off, ulen, blob_fad, R);
        printf("pak %u @0x%08x: %u chunks (%u stored, bounce@%u), %u -> %u B (%.1f%%), "
               "R=%u, FAD %u\n", p, PAKS[p].off, n, nstored, bounce_idx, ulen, S,
               100.0 * S / ulen, R, blob_fad);
        free(plain);
        blob_fad += R / 2048;
        total_blob += R;
        if (p == 0) {   /* entry table after chunk tables; NPAK==1 today */
            fprintf(fh, "static const struct lz4pak_entry lz4pak_map[] = {\n"
                        "    { 0x%08xu, 0x%08xu, %uu, %uu, %uu, %uu, lz4pak_chunks0 },\n"
                        "};\n#define LZ4PAK_NPAK 1\n",
                    PAKS[0].off, ulen, e.blob_fad, R, front, n);
        }
    }
    fprintf(fj, "]\n");
    fclose(in); fclose(fb); fclose(fh); fclose(fj);
    printf("lz4pak: %u B blob, ROUND-TRIP + INVARIANTS PASS\n", total_blob);
    return 0;
}
