#include <kos.h>
#include <arch/timer.h>         /* arch_timer_gettime() -- load-stage timing */
#include "shim_iface.h"
#include "patch_table.h"        /* Task 9: generated by scripts/build_patch_table.py */

extern uint8 shim_bin[];        /* objcopy-embedded shim.bin, see Makefile */
extern uint8 shim_bin_end[];
extern uint8 bios_data[];       /* objcopy-embedded: [BIOS60000_LEN][KERNEL_A/B/C_LEN], see shim_iface.h offsets */
/* Task 10: v2 record walker -- handoff(records_p2, entry); see handoff.S. */
extern void handoff(uint32 records_p2, uint32 entry);
/* ../shims/src/gd.c, compiled into the loader too (Makefile) -- the loader
 * rehearses the shim's runtime raw-ATA read before handoff. */
extern int gd_read_fad(unsigned fad, void *dst, unsigned sectors);
extern unsigned int gd_last_err;
extern uint8 handoff_end[];     /* end-of-stub label in handoff.S (stub is PIC) */

/* ---- staging layout (Task 10) -------------------------------------------
 * THE constraint of this task: KOS links this loader at 0x8c010000 with a
 * ~838 KB footprint, so the running loader occupies 0x8c010000-0x8c0dc000
 * (plus its heap above) -- which contains SHIM_BASE (0x8c010000),
 * BIOS60000_DST (0x8c018000) AND GAME_LOAD_ADDR (0x8c020000)
 * (task-6-report.md §loader/shim load-address collision). Nothing may be
 * written to its final home while loader code/data is live, so every piece is
 * staged HIGH here and reaches its home only inside handoff.S's record
 * walker, which itself runs relocated + uncached out of HANDOFF_SCRATCH.
 * (KERNEL_DST 0x8c000600 sits below the loader image, but it is the DC BIOS's
 * own low RAM -- KOS's live cdrom/syscall world -- so it is staged too, which
 * also keeps the placement rule uniform: one mechanism, no exceptions.)
 *
 * Everything lives above STAGING_ADDR + MAIN_LEN = 0x8ce71ff8 and below the
 * KOS stack top 0x8d000000; the tail ends at ~0x8ce94040, leaving ~1.4 MB of
 * headroom under RAM top. */
#define STAGE_SHIM      0x8ce80000u   /* SHIM_END - SHIM_BASE = 0x8000 */
#define STAGE_BLOB      0x8ce88000u   /* BIOS60000_LEN         = 0x7000 */
#define STAGE_KERNEL    0x8ce8f000u   /* KERNEL_TOTAL_LEN      = 0x3200 */
#define STAGE_RECORDS   0x8ce93000u   /* 5 * 12 B copy records */
#define HANDOFF_SCRATCH 0x8ce94000u   /* the PIC stub, run through its P2 alias */

/* The shim record covers the WHOLE shim window [SHIM_BASE, SHIM_END), not just
 * shim.bin: SHIM_ERR / G1_MIRROR / MAPLE_MIRROR / SHIM_STATE / SHIM_BOUNCE /
 * the GD stack all live in 0x8c014000-0x8c018000, which is loader image right
 * now. A record that stopped at shim.bin's end would leave the game reading
 * loader bytes as its G1 register mirror -- and the mirror invariant
 * (mirror[0x418] == 0 when no DMA is outstanding, docs/kb/phase4-conversion.md
 * §CART-WAIT) would be violated on the first poll. One record, one zero-fill,
 * no separate mirror-zeroing pass. */
#define SHIM_WINDOW     (SHIM_END - SHIM_BASE)      /* 0x8000 */

/* Real-HW visibility: serial is invisible on a TV. Default is quiet --
 * LOADER_QUIET 1 makes say() skip its per-stage framebuffer draws; the
 * splash (KOS init already set 640x480) and halt()'s red screen carry
 * visibility instead. Flip to 0 to have say() draw every stage too; a
 * stuck screen then names the stage that hung. */
#define LOADER_QUIET 1
extern uint8 splash_bin[];      /* objcopy-embedded 640x480 RGB565 (Makefile) */

/* Serial kill-switch (release default 0): serial-SD dongles (DreamShell
 * isoldr) drive their SD card over the SCIF pins, so a release build must
 * never transmit. KOS's dbgio_init is weak (kernel/debug/dbgio.c:110);
 * overriding it with a no-op means no dbgio device is ever selected and
 * dbgio_enabled stays 0, killing all dbglog/printf output from before the
 * KOS boot banner (every dbgio_write_* is guarded, dbgio.c:162-169). Flip to
 * 1 for serial diagnostics (debug builds): make gdi SERIAL=1 (top Makefile). */
#ifndef LOADER_SERIAL
#define LOADER_SERIAL 0
#endif
#if !LOADER_SERIAL
int dbgio_init(void) { return 0; }   /* strong override of KOS weak symbol */
#endif

/* FORCE_SYSCALL=1 (top Makefile): skip the raw rehearsal below and go
 * straight to the syscall backend -- emulator control legs only (Flycast
 * HLEs the GD syscalls statelessly; the real dongle can't be emulated). */
#ifndef GD_FORCE_SYSCALL
#define GD_FORCE_SYSCALL 0
#endif

/* TESTSRV=1 (top Makefile, fix round 2): like FORCE_SYSCALL, but for a
 * shim built with its own GD_TEST_SERVER stand-in (shims/src/gd_testsrv.c)
 * installed at the syscall vector just before handoff, below -- debug
 * round 1 (task-6-report.md) proved FORCE_SYSCALL's leg was structurally
 * invalid (Flycast's real BIOS vector, after this port's own KERNEL-SLICE
 * stomp, serves no real GD driver at all), so this replaces it as the way
 * to actually exercise gdc_call's trampoline end-to-end. Test-only, never
 * shipped. */
#ifndef LOADER_TESTSRV
#define LOADER_TESTSRV 0
#endif

/* FORCE_CARVE=1 (top Makefile, fix round 2): apply the heap-carve tables
 * even on the raw backend -- one-variable isolation of the carve mechanism
 * from backend selection (does the carved heap top break a normal raw-ATA
 * boot, independent of whether the syscall backend ever runs). Test-only,
 * never shipped. */
#ifndef FORCE_CARVE
#define FORCE_CARVE 0
#endif

/* No progress bar (Task 26 ROLLED BACK, operator 2026-09-01): tried
 * shim-side (v1 -- defaced the game's NOW LOADING; the game seizes video
 * before its first cart read) and loader-side (v2 + BOOT-UNBLANK -- on
 * GDEMU the loader's disc load is near-instant, so the bar reads as a
 * blink, and unblanking the boot gap flashed a glitch row). Full autopsy:
 * docs/kb/phase5-hardware.md §Loading bar rollback. */
static int say_row = 0;
static void say(const char *s) {
    dbglog(DBG_INFO, "%s\n", s);
    if (LOADER_QUIET) return;
    bfont_draw_str(vram_s + (40 + say_row * 26) * 640 + 20, 640, 1, s);
    say_row++;
}

static void halt(const char *msg) {
    dbglog(DBG_INFO, "%s", msg);
    for (int i = 0; i < 640 * 480; i++) vram_s[i] = 0xf800;   /* red */
    bfont_draw_str(vram_s + 100 * 640 + 20, 640, 1, msg);
    for(;;) thd_sleep(1000);
}

/* Task 9: table is now { dat_off, img, len, old[12], neu[12], what } and
 * addressed by raw .dat offset (senkosp's patch sites span both the main and
 * test load images, docs/kb/phase4-conversion.md §Cart-patch sites
 * Conventions) instead of Cleopatra's single boot.bin RAM address -- so the
 * loader converts dat_off -> in-buffer offset itself via load_base
 * (MAIN_DAT_OFF/TEST_DAT_OFF), the same subtraction the generator's img_of()
 * boundary is defined against. `table`/`n` let one function drive either
 * image's array; only the main image is loaded this task (Tasks 10-13 bring
 * the test image's own cdrom_read_sectors + apply_patches call online). */
static int apply_patches(uint8 *img, const patch_t *table, unsigned n, uint32 load_base) {
    /* Cross-check: the sub-table must match the image actually loaded. `img`
     * is derived from load_base by the SAME rule as the generator's img_of()
     * (dat_off >= TEST_DAT_OFF -> test), so a table/image mix-up -- the only
     * way p->dat_off - load_base can be a wild in-buffer offset -- is caught
     * before the first memcmp instead of scribbling somewhere random. Abort,
     * not skip: a mismatched table is a build bug, and a half-patched image
     * boots into undefined behaviour. */
    unsigned want_img = (load_base >= TEST_DAT_OFF) ? 1u : 0u;
    for (unsigned i = 0; i < n; i++) {
        const patch_t *p = &table[i];
        uint8 *at = img + (p->dat_off - load_base);
        if (p->img != want_img) {
            dbglog(DBG_INFO, "PATCH IMG MISMATCH %s @dat:%08lx img=%u want=%u\n",
                   p->what, (unsigned long)p->dat_off, p->img, want_img);
            return -1;
        }
        if (memcmp(at, p->old, p->len)) {
            dbglog(DBG_INFO, "PATCH MISMATCH %s @dat:%08lx\n", p->what,
                   (unsigned long)p->dat_off);
            return -1;
        }
        memcpy(at, p->neu, p->len);
        dbglog(DBG_INFO, "patched %s @dat:%08lx (%u)\n", p->what,
               (unsigned long)p->dat_off, p->len);
    }
    return 0;
}

int main(void) {
    dbglog(DBG_INFO, "SENKOSP LOADER PHASE4 TASK10\n");

    /* Naomi BIOS splash (arcade boot feel): shown for the whole load. On the
     * real Naomi the BIOS draws this screen, not the game -- our conversion
     * bypasses that BIOS, so the loader stands in for it. Displayed as
     * RGB565: senkosp's OWN takeover format, pinned Task 26 (FB_R_CTRL
     * settles 0x00800005, fb_depth=01=565, game writer pc=8c032140 --
     * captures/attract-s2.stdout.log; replaces the carried Cleopatra 0555
     * assumption, whose repack showed cyan-white after takeover, HW round-1
     * photo). Splash bytes thus scan right through takeover until the game
     * blanks for its own boot scene. KOS picks the cable-correct 640x480
     * variant. */
    if (LOADER_QUIET) {
        vid_set_mode(DM_640x480, PM_RGB565);
        memcpy(vram_s, splash_bin, 640 * 480 * 2);
    }

    say("SENKOSP LOADER PHASE4 TASK10");

    /* Boot-combo: hold A+Start on pad 1 during boot -> test image (spec
     * Decision 1). maple_wait_scan() first: maple_init() only STARTS the
     * periodic scan, so enumerating before the first scan lands would read
     * "no controller" and silently never select test mode. */
#ifndef LOADER_FORCE_TEST_BOOT
#define LOADER_FORCE_TEST_BOOT 0   /* Task 13 diagnostic (LOADER_SERIAL precedent):
                                    * transient -- forces the test-image path with
                                    * no operator holding the combo, so the
                                    * unattended testboot-diag leg can prove the
                                    * boot half of criterion 4. Revert to 0 before
                                    * commit; the real combo check below still
                                    * runs and can only ever ADD test_boot=1, so a
                                    * live A+Start still works either way. */
#endif
    int test_boot = LOADER_FORCE_TEST_BOOT;
    maple_wait_scan();
    {
        maple_device_t *cont = maple_enum_type(0, MAPLE_FUNC_CONTROLLER);
        if (cont) {
            cont_state_t *st = (cont_state_t *)maple_dev_status(cont);
            if (st && (st->buttons & CONT_A) && (st->buttons & CONT_START))
                test_boot = 1;
        }
    }
    uint32 img_off = test_boot ? TEST_DAT_OFF : MAIN_DAT_OFF;
    uint32 img_len = test_boot ? TEST_LEN     : MAIN_LEN;
    say(test_boot ? "boot combo: TEST image" : "boot: MAIN image");

    cdrom_reinit();             /* inits the GD subsystem */
    say("GD init OK");

    /* TEST_DAT_OFF (0x171ff8) is NOT sector-aligned: read from the containing
     * sector and let the image start `skip` bytes into the buffer. `skip` is
     * 4-aligned (0x7f8 % 4 == 0), which the copy record needs. Main is
     * skip == 0, i.e. exactly the read Task 8 verified. */
    uint32 skip = img_off % 2048;
    uint32 fad  = CART_FAD + img_off / 2048;
    uint32 secs = (skip + img_len + 2047) / 2048;
    uint8 *buf   = (uint8 *)STAGING_ADDR;
    uint8 *stage = buf + skip;
    if (cdrom_read_sectors(buf, fad, secs) != ERR_OK)
        halt("KOS GD READ FAIL");
    /* Magic check only for the main image: the "NAOMI" header IS the first
     * bytes of the main load entry (ROM 0 -> RAM 0x8c020000, docs/kb/game.md
     * §Parsed .dat header). The test entry is raw code with no signature. */
    if (!test_boot && memcmp(stage, "NAOMI", 5)) {
        dbglog(DBG_INFO, "bad image: %02x %02x %02x %02x %02x %02x %02x %02x @FAD %d\n",
               stage[0], stage[1], stage[2], stage[3],
               stage[4], stage[5], stage[6], stage[7], (int)fad);
        halt("BAD IMAGE (KOS READ)");
    }
    say("cart read OK (KOS)");

    /* Phase 7 T1: which GD backend the rehearsal below picks. Function scope
     * (not block-scoped inside the rehearsal below) because it must survive
     * to the staging seed (SHIM_STATE[1]) and the conditional carve, both
     * well after the rehearsal block closes. */
    uint32 backend = 0;                 /* 0 = raw, 1 = syscall */

    /* Rehearse the shim's exact runtime GD path before handing the game to it
     * (replaces Cleopatra's syscall rehearsal -- our runtime path is raw ATA,
     * because the kernel slice this loader places lands on the BIOS's low-RAM
     * GD state; see shims/src/gd.c's header). Same sector KOS just read, so a
     * mismatch is the driver's fault, not the disc's. Runs BEFORE
     * apply_patches, which mutates `stage`.
     * Phase 7 T1: a raw-path failure is now expected, not fatal -- under
     * DreamShell isoldr virtualizes the GD only at the syscall layer, the
     * physical drive still holds the DS boot disc, so raw ATA reads nothing
     * of ours. Falls back to rehearsing the syscall backend on the same
     * sector; `backend` (function scope, see declaration above) records
     * which one won and stays live through staging below. */
    {
        static uint8 rawbuf[2048] __attribute__((aligned(32)));
        int gd_sys_read_sectors(void *dst, unsigned fad, unsigned n);
        /* The driver writes rawbuf through its P2 (uncached) alias. KOS's
         * startup zeroed this .bss buffer through the CACHED alias, so its
         * lines may still be in the D-cache and dirty -- invalidate (discard,
         * no write-back: a write-back would land stale zeroes on top of the
         * incoming sector) so the memcmp below reads what the drive delivered. */
        dcache_inval_range((uintptr_t)rawbuf, sizeof(rawbuf));
#if !GD_FORCE_SYSCALL && !LOADER_TESTSRV
        /* KOS is live here: its cdrom driver pumps the BIOS GD server from a
         * vblank handler whenever a DMA is outstanding (KOS cdrom.c:691-708).
         * None is outstanding after a blocking cdrom_read_sectors, but a raw
         * task-file transaction must not be interleaved with one under any
         * timing -- so take the whole ~1 ms transfer with IRQs off. */
        irq_mask_t old = irq_disable();
        int r = gd_read_fad(fad, rawbuf, 1);
        irq_restore(old);
#else
        int r = -99;           /* FORCE_SYSCALL/TESTSRV build: skip raw */
#endif
        if (r != 0) {
            uint32 raw_err = gd_last_err; (void)raw_err;
#if LOADER_TESTSRV
            /* TESTSRV installs GD_TEST_SERVER at the syscall vector only at
             * staging, just before handoff (below) -- it isn't live yet
             * here, so calling gd_sys_read_sectors now would jump into
             * whatever the vector still holds (fix round 2, task-6-report.md
             * DEBUG ROUND 1: on this leg's BIOS that's real-but-stomped GD
             * driver code, not our stand-in). Skip the rehearsal call
             * itself; the shim's live syscall path gets its first exercise
             * post-handoff, in-game, against the now-installed server. */
            backend = 1;
            say("cart read OK (syscall) [TESTSRV]");
#else
            /* Raw path failed (DreamShell: expected -- isoldr virtualizes GD
             * at the syscall layer only; the physical drive holds the DS boot
             * disc). Rehearse the syscall backend on the same sector. KOS is
             * live and its own driver already pumps this server; no IRQ mask
             * (Cleopatra loader rehearsal precedent). Buffer passed as P2 --
             * isoldr stores through the given pointer, PIOREAD doesn't purge. */
            dcache_inval_range((uintptr_t)rawbuf, sizeof(rawbuf));
            /* Only an isoldr-class resident survives our handoff (the
             * kernel slice stomps the 0x8c0010xx BIOS syscall RAM --
             * task-6-report.md DEBUG ROUND 1), so a working server alone
             * is NOT enough to pick the syscall backend: the live stock
             * BIOS would pass this rehearsal, then wedge silently
             * in-game. Same two-signature fingerprint as gdstack.S's
             * MMU gate (gdstack.S:104-118): vector pair +8, or GD entry
             * placed above the BIOS syscall RAM. */
            uint32 vbc = *(volatile uint32 *)P2ADDR(0x8c0000bc);
            uint32 vc0 = *(volatile uint32 *)P2ADDR(0x8c0000c0);
            if (!(vc0 == vbc + 8 || (vbc & 0x00ffffffu) >= 0x00010000u)) {
                char msg[96];
                sprintf(msg, "GD FAIL raw r=%d e=%08lx / no isoldr vec=%08lx",
                        r, (unsigned long)raw_err, (unsigned long)vbc);
                halt(msg);
            }
            int rs = gd_sys_read_sectors((void *)P2ADDR((uint32)rawbuf), fad, 1);
            if (rs != 0) {
                char msg[96];
                sprintf(msg, "GD FAIL raw r=%d e=%08lx / sys r=%d e=%08lx",
                        r, (unsigned long)raw_err,
                        rs, (unsigned long)gd_last_err);
                halt(msg);
            }
            if (memcmp(rawbuf, buf, 2048))
                halt("SYSCALL MISMATCH VS KOS READ");
            backend = 1;
            say("cart read OK (syscall)");
#endif
        } else {
            if (memcmp(rawbuf, buf, 2048))
                halt("RAW-ATA MISMATCH VS KOS READ");
            say("cart read OK (raw ATA)");
        }
    }

    if (apply_patches(stage,
                      test_boot ? senkosp_patches_test : senkosp_patches_main,
                      test_boot ? N_PATCHES_TEST : N_PATCHES_MAIN,
                      img_off))
        halt("PATCH ABORT");
    dbglog(DBG_INFO, "patch table: %u main / %u test entries (applied: %s)\n",
           (unsigned)N_PATCHES_MAIN, (unsigned)N_PATCHES_TEST,
           test_boot ? "test" : "main");
    say("patches OK");

    /* Phase 7 T1 heap carve (task-3b-report.md): applied on the syscall
     * backend, and only AFTER the unconditional table above (its `old`
     * encodes the post-reloc state -- task-3b-report.md FIX ROUND 1).
     * `backend` defaults to 0 and is set to 1 nowhere except the syscall
     * branch above, so a real-BIOS/raw-ATA boot never reaches this block on
     * its own -- the raw path is provably un-carved UNLESS FORCE_CARVE=1
     * (fix round 2 test knob) explicitly asks for it anyway, to isolate the
     * carve from backend selection. */
    if (backend || FORCE_CARVE) {
        if (apply_patches(stage,
                          test_boot ? senkosp_carve_test : senkosp_carve_main,
                          test_boot ? N_CARVE_TEST : N_CARVE_MAIN,
                          img_off))
            halt("CARVE ABORT");
        say("heap carved for isoldr");
    }

    /* ---- staging (Task 10) ----------------------------------------------
     * Nothing below is written to its FINAL home: see the STAGE_* block at the
     * top for why (the loader's own image covers SHIM_BASE, BIOS60000_DST and
     * GAME_LOAD_ADDR). Each piece is assembled here, high in RAM, and the
     * record walker moves it after the loader is out of the picture. */

    /* Whole shim window: shim.bin, then zero to SHIM_END. The zero-fill is
     * both the shim's .bss (NOBITS -- absent from shim.bin, so uninitialised
     * on real DC where RAM boots as garbage) and the fixed data blocks
     * SHIM_ERR / G1_MIRROR / MAPLE_MIRROR / SHIM_BOUNCE / GD stack. A zeroed
     * G1_MIRROR is exactly the mirror invariant's initial state: mirror[0x418]
     * (SB_GDST) reads 0, so every config-time SB_GDST poll falls straight
     * through instead of spinning on stale bytes. */
    uint32 shim_len = (uint32)(shim_bin_end - shim_bin);
    if (shim_len > SHIM_CODE_MAX) halt("SHIM TOO BIG");
    memcpy((void *)STAGE_SHIM, shim_bin, shim_len);
    memset((void *)(STAGE_SHIM + shim_len), 0, SHIM_WINDOW - shim_len);
    /* SHIM_STATE[0] = boot mode (0 = main, 1 = test), read by the shim. */
    *(uint32 *)(STAGE_SHIM + (SHIM_STATE - SHIM_BASE)) = (uint32)test_boot;
    /* SHIM_STATE[1] = GD backend from the rehearsal probe (0 raw, 1 syscall). */
    *(uint32 *)(STAGE_SHIM + (SHIM_STATE - SHIM_BASE) + 4) = backend;
    /* Canary under the private syscall stack (gd_sys.c checks per read). */
    *(uint32 *)(STAGE_SHIM + (GD_STACK_BOTTOM - SHIM_BASE)) = GD_STACK_CANARY;

    /* The BIOS-derived blocks the game reads via patched P2 pointers: the
     * 0x60000 verify+copy library, and the three-piece Naomi RTOS kernel slice
     * (KERNEL-SLICE pin, docs/kb/phase4-conversion.md). bios_data.bin's layout
     * (loader/Makefile) matches these offsets exactly. */
    memcpy((void *)STAGE_BLOB, bios_data + BIOS_DATA_60000_OFF, BIOS60000_LEN);
    memcpy((void *)STAGE_KERNEL, bios_data + BIOS_DATA_KERNEL_A_OFF,
           KERNEL_TOTAL_LEN);   /* A|B|C are contiguous in both blob and RAM */

    /* Copy records, staged high like everything else: a records[] in loader
     * .data would sit inside the game image's own copy destination and be
     * shredded by the first record while the walker still needs it. */
    struct rec { uint32 src, dst, len; };
    struct rec *rec = (struct rec *)STAGE_RECORDS;
    unsigned n = 0;
    rec[n].src = P2ADDR((uint32)stage);     rec[n].dst = P2ADDR(GAME_LOAD_ADDR); rec[n++].len = img_len;
    rec[n].src = P2ADDR(STAGE_SHIM);        rec[n].dst = P2ADDR(SHIM_BASE);      rec[n++].len = SHIM_WINDOW;
    rec[n].src = P2ADDR(STAGE_KERNEL);      rec[n].dst = P2ADDR(KERNEL_DST);     rec[n++].len = KERNEL_TOTAL_LEN;
    rec[n].src = P2ADDR(STAGE_BLOB);        rec[n].dst = P2ADDR(BIOS60000_DST);  rec[n++].len = BIOS60000_LEN;
    rec[n].src = 0; rec[n].dst = 0; rec[n++].len = 0;                   /* terminator */

    /* Relocate the PIC handoff stub out of every copy destination. */
    uint32 ho_len = (uint32)((uint8 *)handoff_end - (uint8 *)handoff);
    memcpy((void *)HANDOFF_SCRATCH, (void *)handoff, ho_len);

    /* Write-back every CPU store above to RAM: the stub reads records and
     * sources through P2 (uncached), so anything still sitting dirty in the
     * D-cache would be invisible to it -- and the CCR write at the end of the
     * stub INVALIDATES the cache, discarding it for good. */
    dcache_purge_range(STAGING_ADDR, skip + img_len);
    dcache_purge_range(STAGE_SHIM, SHIM_WINDOW);
    dcache_purge_range(STAGE_BLOB, BIOS60000_LEN);
    dcache_purge_range(STAGE_KERNEL, KERNEL_TOTAL_LEN);
    dcache_purge_range(STAGE_RECORDS, n * sizeof(struct rec));
    dcache_purge_range(HANDOFF_SCRATCH, ho_len);

    dbglog(DBG_INFO, "records=%u img=%08lx/%lx shim=%08x/%x kern=%08x/%x blob=%08x/%x\n",
           n, (unsigned long)stage, (unsigned long)img_len,
           (unsigned)SHIM_BASE, (unsigned)SHIM_WINDOW,
           (unsigned)KERNEL_DST, (unsigned)KERNEL_TOTAL_LEN,
           (unsigned)BIOS60000_DST, (unsigned)BIOS60000_LEN);
    say("staged: shim + BIOS data + records");
    dbglog(DBG_INFO, "jumping to %08x\n", GAME_ENTRY);
    say("HANDOFF -> game");
    irq_disable();
    /* Deliberately NO TMU stop / ARM reset here (Cleopatra's proven reasoning
     * carried over -- the game reads TCNT0 for delay loops and resets the
     * AICA ARM itself as its first action). */

    /* MMU OFF for the game. */
    *(volatile uint32 *)0xff000010 = 0;            /* MMUCR: AT=0, TLB invalid */

    /* TA/PVR to BIOS-fresh state (Cleopatra DreamShell round 11, carried over
     * -- see Cleopatra's loader/main.c for the full HW-round citation). */
    *(volatile uint32 *)0xa05f8008 = 3;
    (void)*(volatile uint32 *)0xa05f8008;          /* posted-write flush */
    *(volatile uint32 *)0xa05f8008 = 0;
    *(volatile uint32 *)0xa05f6900 = 0xffffffff;   /* ISTNRM: clear latches */
    *(volatile uint32 *)0xa05f690c = 0xffffffff;   /* ISTERR: clear latches */

#if LOADER_TESTSRV
    /* Test-only vector install (TESTSRV, fix round 2): 0x8c0000bc/-c0 sit
     * below every copy record above (shim home starts at SHIM_BASE
     * 0x8c010000), so they're poked directly here, last, right before the
     * jump. GD_TEST_SERVER_ADDR (patch_table.h, resolved from shim.map the
     * same way hook()/detour() targets are) is the shim's own link address
     * for gd_test_server -- valid once the record walker below has copied
     * the shim window to SHIM_BASE, which happens inside ho() before the
     * game's first instruction ever runs, so nothing dereferences this
     * vector before it is correct. [0xc0] = [0xbc]+8 mimics isoldr's own
     * vector pair (real isoldr installs both, 8 B apart) so gdstack.S's own
     * fingerprint probe reads this as isoldr-class and applies its MMU
     * AT=0 window -- the whole point of the exercise (task-6-report.md
     * DEBUG ROUND 1 / FIX ROUND 2). Never shipped (top Makefile). */
    if (GD_TEST_SERVER_ADDR == 0)
        halt("TESTSRV ADDR 0 (stale patch_table.h -- make clean)");
    *(volatile uint32 *)P2ADDR(0x8c0000bc) = GD_TEST_SERVER_ADDR;
    *(volatile uint32 *)P2ADDR(0x8c0000c0) = GD_TEST_SERVER_ADDR + 8;
#endif

    void (*ho)(uint32, uint32) =
        (void *)P2ADDR(HANDOFF_SCRATCH);           /* run the stub uncached */
    ho(P2ADDR(STAGE_RECORDS), GAME_ENTRY);

    halt("HANDOFF RETURNED");                      /* unreachable */
    return 0;
}
