/* GENERATED by scripts/gen_menu_assets.py from scripts/menu_def.py -- do not edit. Committed alongside the PNGs it describes. */
#ifndef MENU_LAYOUT_H
#define MENU_LAYOUT_H

typedef struct { unsigned short x, y, w, h; } mrect_t;

#define MENU_SHEET_W 640
#define MENU_BG_COLOR 0xe71c

static const mrect_t MENU_TOP_LABEL[3][2] = {
  {{0,0,320,36}, {320,0,320,36}},
  {{0,36,320,36}, {320,36,320,36}},
  {{0,72,320,36}, {320,72,320,36}},
};

static const unsigned short MENU_TOP_DEST[3][2] = {
  {160, 178},
  {160, 222},
  {160, 266},
};

static const mrect_t MENU_TOP_FOOTER = {0,108,640,24};
#define MENU_TOP_FOOTER_X 0
#define MENU_TOP_FOOTER_Y 452

#define MENU_N_SETTINGS 8
#define MENU_MAX_VALUES 8

static const mrect_t MENU_SET_LABEL[8][2] = {
  {{0,164,288,28}, {288,164,288,28}},
  {{0,248,288,28}, {288,248,288,28}},
  {{288,332,288,28}, {0,360,288,28}},
  {{288,360,288,28}, {0,388,288,28}},
  {{288,500,288,28}, {0,528,288,28}},
  {{0,584,288,28}, {288,584,288,28}},
  {{0,612,288,28}, {288,612,288,28}},
  {{0,668,288,28}, {288,668,288,28}},
};

static const mrect_t MENU_SET_VALUE[8][8] = {
  {{0,192,288,28}, {288,192,288,28}, {0,220,288,28}, {288,220,288,28}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}},
  {{0,276,288,28}, {288,276,288,28}, {0,304,288,28}, {288,304,288,28}, {0,332,288,28}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}},
  {{0,276,288,28}, {288,276,288,28}, {0,304,288,28}, {288,304,288,28}, {0,332,288,28}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}},
  {{288,388,288,28}, {0,416,288,28}, {288,416,288,28}, {0,444,288,28}, {288,444,288,28}, {0,472,288,28}, {288,472,288,28}, {0,500,288,28}},
  {{288,444,288,28}, {0,472,288,28}, {288,472,288,28}, {0,500,288,28}, {288,528,288,28}, {0,556,288,28}, {288,556,288,28}, {0,0,0,0}},
  {{288,388,288,28}, {0,416,288,28}, {288,416,288,28}, {0,444,288,28}, {288,444,288,28}, {0,472,288,28}, {288,472,288,28}, {0,500,288,28}},
  {{0,640,288,28}, {288,640,288,28}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}},
  {{0,640,288,28}, {288,640,288,28}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}, {0,0,0,0}},
};

static const unsigned char MENU_SET_NVAL[8] = {4, 5, 5, 8, 7, 8, 2, 2};
static const unsigned char MENU_SET_IDX[8] = {6, 7, 8, 10, 12, 14, 4, 5};
static const unsigned char MENU_SET_IDX2[8] = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff};   /* unused: no 2-byte rows in this recon */

static const unsigned char MENU_SET_BYTE[8][8] = {
  {0x00, 0x01, 0x02, 0x03, 0, 0, 0, 0},
  {0x01, 0x02, 0x03, 0x04, 0x05, 0, 0, 0},
  {0x01, 0x02, 0x03, 0x04, 0x05, 0, 0, 0},
  {0x32, 0x3c, 0x46, 0x50, 0x5a, 0x64, 0x6e, 0x78},
  {0x5a, 0x64, 0x6e, 0x78, 0x82, 0x8c, 0x96, 0},
  {0x32, 0x3c, 0x46, 0x50, 0x5a, 0x64, 0x6e, 0x78},
  {0x00, 0x01, 0, 0, 0, 0, 0, 0},
  {0x00, 0x01, 0, 0, 0, 0, 0, 0},
};

static const unsigned char MENU_SET_BYTE2[8][8] = {   /* unused: no 2-byte rows in this recon */
  {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0},
  {0, 0, 0, 0, 0, 0, 0, 0},
};

#define MENU_SET_LABEL_X 48
#define MENU_SET_VALUE_X 344
#define MENU_SET_ROW_Y(i) (96 + (i) * 34)

static const mrect_t MENU_SET_TITLE = {0,132,640,32};
#define MENU_SET_TITLE_X 0
#define MENU_SET_TITLE_Y 40

static const mrect_t MENU_SET_FOOTER = {0,696,640,24};
#define MENU_SET_FOOTER_X 0
#define MENU_SET_FOOTER_Y 452

#define MENU_DEFAULT_RECORD {0x23, 0x51, 0x17, 0x03, 0x00, 0x01, 0x01, 0x02, 0x02, 0x00, 0x46, 0x00, 0x96, 0x00, 0x46, 0x00}

/* ---- CONTROLS pages (controls_pad.png / controls_stick.png) ----
 * CTL_*_FUNC index FUNC_WORDS/CTL_WORD; button order is
 * menu_def.py's PAD_BUTTONS / STICK_BUTTONS, same order as
 * shims/src/layouts.h's JVS_LAYOUT_* rows. CTL_*_ANCHOR is the
 * chip's top-left on the page. The footer is baked into both
 * pages -- nothing to blit. */
#define CTL_N_BUTTONS 6
#define CTL_FUNC_NONE 5   /* chips with this func are skipped (stick B has no row) */
static const mrect_t CTL_WORD[6] = {{0,720,126,24}, {126,720,126,24}, {252,720,126,24}, {378,720,126,24}, {504,720,126,24}, {0,744,126,24}};   /* MAIN, SUB, BARRAGE, ACTION, OVERDRIVE, NONE */

static const unsigned char CTL_PAD_FUNC[2][6] = {
  {0, 1, 2, 3, 4, 3},   /* TOURNAMENT */
  {0, 3, 1, 2, 3, 4},   /* CLASSIC */
};
static const unsigned char CTL_STICK_FUNC[6] = {3, 5, 0, 1, 2, 4};

static const unsigned short CTL_PAD_ANCHOR[6][2] = {
  {506, 165},   /* A */
  {506, 133},   /* B */
  {506, 197},   /* X */
  {506, 101},   /* Y */
  {60, 60},   /* LTRIG */
  {506, 60},   /* RTRIG */
};
static const unsigned short CTL_STICK_ANCHOR[6][2] = {
  {506, 195},   /* A */
  {506, 229},   /* B */
  {506, 59},   /* X */
  {506, 93},   /* Y */
  {506, 127},   /* Z */
  {506, 161},   /* C */
};

static const mrect_t CTL_ROW_LABEL[3][2] = {
  {{126,744,288,28}, {0,772,288,28}},
  {{288,772,288,28}, {0,800,288,28}},
  {{288,800,288,28}, {0,828,288,28}},
};
static const mrect_t CTL_PAD_VALUE[2] = {{288,828,288,28}, {0,856,288,28}};
static const mrect_t CTL_STICK_VALUE = {288,856,288,28};

#define CTL_ROW_LABEL_X 48
#define CTL_ROW_VALUE_X 344
#define CTL_ROW_Y(i) (352 + (i) * 34)

#endif /* MENU_LAYOUT_H */
