#!/usr/bin/env python3
"""Extract senkosp's own MIE reply blobs from a Naomi-mode capture, for the
shim's maple service (Phase 4 Task 11).

Adapted from ../cleopatra/scripts/extract_jvs_replies.py. Differences, all
forced by this port's evidence:

  1. **Post-handoff only.** `docs/kb/phase4-conversion.md` §R5 proved the
     pre-`MAINHANDOFF` maple traffic is the *Naomi BIOS*, not senkosp: its
     replies go to the BIOS's own buffer (0x0c296220) and are not what the
     game parses. Everything harvested here is from after the marker, i.e.
     senkosp's own transactions.
  2. **Lengths come from the log, not from a model.** The fork prints
     `MDODMA rawdma_ret outlen=` immediately before each `MIERESP`
     (`../flycast4naomi2dreamcast/core/hw/maple/maple_if.cpp:283-306`), so the
     true reply length is measured, never inferred. It matters: JVS data
     frames declare one 32-bit word MORE than they write
     (`receive_jvs_messages`, `maple_jvs.cpp:1716-1727`:
     `dword_length = (len + 22) / 4 + 1`), so Cleopatra's `(hdr[3]+1)*4` rule
     overshoots them by 4 bytes.
  3. **Three classes are longer than the 0x40-byte MIERESP dump** and are
     reconstructed here, each with an assert that ties the reconstruction to
     bytes the capture *does* contain:
       sub 0x33 (68 B)  captured 64 + the 4-byte tail of the trailing ack
                        frame `18 00 8e 00` (`maple_jvs.cpp:1888-1893`);
                        checked against the separately captured sub-0x17 ack.
       jvs 0x10 (92 B)  the board-ID string (`maple_jvs.cpp:1105` get_id()),
                        spliced onto the captured prefix, JVS checksum
                        recomputed (Cleopatra's method, unchanged).
       sub 0x03 (132 B) the 128-byte EEPROM image, rebuilt from the captured
                        first 60 bytes using the Naomi dual-copy layout
                        (system section twice, game header twice, game data
                        twice); every copy the capture contains is asserted
                        equal to its twin before the tail is derived.

Output: shims/build/mie_blobs.c -- generated, gitignored, regenerated by the
shim Makefile. It is captured game/BIOS traffic, so the bytes are never
committed; this script and the provenance note are.

Usage: python3 scripts/extract_mie_blobs.py [capture.log] [--out DIR]
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_LOG = os.path.join(REPO, "captures/phase4/pc2.log")

# Board ID, verbatim from the fork that produced the capture
# (../flycast4naomi2dreamcast/core/hw/maple/maple_jvs.cpp:1105 get_id()).
BOARD_ID = b"SEGA ENTERPRISES,LTD.;I/O BD JVS;837-13551 ;Ver1.00;98/10"

# JVS-command -> a unique substring of its sub-0x15 reply's data= hex field.
# (E0 sync at frame byte 0x1a; body = <status> <report> <payload> <checksum>.)
# Byte-identical to Cleopatra's signature table -- both games talk to the same
# emulated MIE, so the enumeration replies are the same bytes.
SIGS = {
    0xF1: "e000040101050b",          # set-address ack
    0x10: "e0003d01015345474120",    # read-ID: "SEGA " prefix, JVS len 0x3d
    0x11: "e00004010111",            # command format rev 1.1
    0x12: "e00004010120",            # JVS rev 2.0
    0x13: "e00004010110",            # communication rev 1.0
    0x14: "e00014010101020d",        # slave features (function list)
}

# Emitted symbols: name -> (class key, required?)
WANT = [
    ("mie_sub01", ("sub", 0x01)), ("mie_sub03", ("sub", 0x03)),
    ("mie_sub13", ("sub", 0x13)), ("mie_sub17", ("sub", 0x17)),
    ("mie_sub21", ("sub", 0x21)), ("mie_sub31", ("sub", 0x31)),
    ("mie_sub33", ("sub", 0x33)), ("mie_86empty", ("sub", 0xFF)),
    ("mie_jvsf1", ("jvs", 0xF1)), ("mie_jvs10", ("jvs", 0x10)),
    ("mie_jvs11", ("jvs", 0x11)), ("mie_jvs12", ("jvs", 0x12)),
    ("mie_jvs13", ("jvs", 0x13)), ("mie_jvs14", ("jvs", 0x14)),
    ("mie_jvsdflt", ("jvs", -1)),
]


def jvs_checksum(b, e0, csum_idx):
    """JVS checksum = sum of the bytes after the E0 sync up to (not incl.) the
    checksum, & 0xff (maple_jvs.cpp:2487-2489; shims/src/jvs.c)."""
    return sum(b[e0 + 1:csum_idx]) & 0xFF


def harvest(path):
    """{class_key: (bytes_captured_up_to_0x40, true_outlen)} from the
    post-MAINHANDOFF MIERESP lines, asserting byte-stability per class."""
    classes, seen = {}, {}
    post, outlen = False, None
    for line in open(path, errors="ignore"):
        if line.startswith("MAINHANDOFF"):
            post = True
            continue
        if not post:
            continue
        if line.startswith("MDODMA rawdma_ret"):
            outlen = int(line.split("outlen=")[1].strip(), 16)
            continue
        if not line.startswith("MIERESP"):
            continue
        m = re.match(r"MIERESP sub=(\S+) addr=(\S+) data=(\S+)", line)
        sub, data = int(m.group(1), 16), m.group(3)
        # NB `sub` is the fork logger's `p_data[4]` (maple_if.cpp:299), which
        # for a payload-less 0x86 frame reads PAST the frame -- that is where
        # the boot driver's site-D "sub=ff" comes from. It is emitted as
        # mie_86empty and the shim keys it on plen, not on the byte.
        if sub == 0x15:
            key = ("jvs", next((c for c, s in SIGS.items() if s in data), -1))
        else:
            key = ("sub", sub)
        raw = bytes.fromhex(data)
        if key in classes:
            # Byte-stability across every occurrence in the leg. The steady
            # sub-0x33 poll is deliberately excluded: it carries live input
            # AND the cold/no-scan variant, so it is NOT stable by nature --
            # the has-data variant (subresp 0x16) is the one the shim replays.
            prev, prevlen = classes[key]
            if (prev, prevlen) != (raw, outlen) and key != ("sub", 0x33):
                sys.exit(f"UNSTABLE {key}: {prev.hex()} @{prevlen:#x}\n"
                         f"          vs {raw.hex()} @{outlen:#x}")
        if key == ("sub", 0x33) and raw[4] != 0x16:
            continue                      # cold (0x32) variant: not replayed
        classes[key] = (raw, outlen)
        seen[key] = seen.get(key, 0) + 1
    return classes, seen


def rebuild_sub33(raw, sub17):
    """68 B: the 64 captured bytes + the last 4 of the trailing ack frame.
    A sub-0x33 reply is TWO maple frames -- the JVS data frame, then
    `reply(MDRS_JVSReply,1); w8(0x18); w8(channel); w8(sense_line); w8(0)`
    (maple_jvs.cpp:1888-1893). The dump stops 4 bytes into the ack, so bytes
    60..63 are its header; the tail is the same 4 payload bytes the separately
    captured sub-0x17 ack carries (same emitter, same channel/node)."""
    assert len(raw) == 64 and len(sub17) >= 8, "sub33/sub17 capture too short"
    assert raw[60:64] == sub17[0:4], (
        f"sub33 tail is not an ack header: {raw[60:64].hex()} != {sub17[0:4].hex()}")
    return raw + sub17[4:8]


def rebuild_jvs10(raw):
    """92 B: splice the full board-ID string onto the captured prefix and
    recompute the JVS checksum (Cleopatra's method, unchanged)."""
    e0 = raw.index(0xE0)
    jvs_len = raw[e0 + 2]
    csum_idx = (e0 + 2) + jvs_len
    assert raw[e0 + 5:e0 + 5 + 33] == BOARD_ID[:33], "board-ID prefix mismatch"
    b = bytearray(raw[3] * 4)             # true length (declared words * 4)
    b[:e0 + 5] = raw[:e0 + 5]
    b[e0 + 5:e0 + 5 + len(BOARD_ID)] = BOARD_ID
    b[e0 + 5 + len(BOARD_ID)] = 0x00      # string terminator
    assert csum_idx == e0 + 5 + len(BOARD_ID) + 1, "board-ID length model wrong"
    b[csum_idx] = jvs_checksum(b, e0, csum_idx)
    return bytes(b)


def rebuild_sub03(raw):
    """132 B: 4-byte maple header + the 128-byte EEPROM image
    (maple_jvs.cpp:1931-1940 -- `reply(MDRS_JVSReply, sizeof(eeprom)/4)` then
    the image at frame offset 4). The dump holds bytes 0..59 of the image;
    the rest follows from the Naomi dual-copy layout, which the captured part
    proves in full:
        0x00 system copy 1 (18 B)   0x12 system copy 2 (18 B)  -- asserted equal
        0x24 game header  1 (4 B)   0x28 game header  2 (4 B)  -- asserted equal
        0x2c game data    1 (n B)   0x2c+n game data 2 (n B)   -- n from header
        tail: zero
    (Layout corroborated by the game-era reply this repo's KB decodes,
    docs/kb/phase4-conversion.md §EEPROM replies.)"""
    ee = bytearray(128)
    ee[:60] = raw[4:64]
    assert ee[0:18] == ee[18:36], "EEPROM system copies differ -- layout wrong"
    assert ee[0x24:0x28] == ee[0x28:0x2C], "EEPROM game headers differ"
    n = ee[0x26]                          # game-section data length
    assert n == ee[0x2A] and 0 < n <= 16, f"game-section length {n} unusable"
    assert 0x2C + 2 * n <= 128, "game section overruns the image"
    ee[0x2C + n:0x2C + 2 * n] = ee[0x2C:0x2C + n]     # copy 2 = copy 1
    return raw[0:4] + bytes(ee)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    out_dir = os.path.join(REPO, "shims/build")
    if "--out" in sys.argv:
        out_dir = sys.argv[sys.argv.index("--out") + 1]
    log = args[0] if args else DEFAULT_LOG
    classes, seen = harvest(log)

    blobs = {}
    for name, key in WANT:
        if key not in classes:
            sys.exit(f"{name}: no {key} reply in {log} (post-MAINHANDOFF)")
        raw, outlen = classes[key]
        if key == ("sub", 0x33):
            blob = rebuild_sub33(raw, classes[("sub", 0x17)][0])
        elif key == ("jvs", 0x10):
            blob = rebuild_jvs10(raw)
        elif key == ("sub", 0x03):
            blob = rebuild_sub03(raw)
        else:
            assert outlen <= 64, f"{name}: {outlen:#x} B reply, dump is 0x40"
            blob = raw[:outlen]
        assert len(blob) == outlen, f"{name}: {len(blob)} B != outlen {outlen:#x}"
        blobs[name] = blob

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "mie_blobs.c")
    with open(path, "w") as f:
        f.write("/* GENERATED by scripts/extract_mie_blobs.py -- do not edit,\n"
                " * do not commit (captured MIE traffic).\n"
                f" * source: {os.path.relpath(log, REPO)} (post-MAINHANDOFF) */\n")
        for name, _ in WANT:
            b = blobs[name]
            rows = ",\n    ".join(
                ",".join(f"0x{x:02x}" for x in b[i:i + 12])
                for i in range(0, len(b), 12))
            f.write(f"const unsigned char {name}[] = {{\n    {rows}\n}};\n"
                    f"const unsigned int {name}_len = {len(b)};\n")
    for name, key in WANT:
        print(f"{name:<12} {len(blobs[name]):3d} B  "
              f"({seen[key]}x in leg)")
    print(f"OK: wrote {len(blobs)} blobs to {os.path.relpath(path, REPO)}")


if __name__ == "__main__":
    main()
