/* GENERATED by scripts/gen_menu_assets.py from scripts/menu_def.py --
 * do not edit. Consumed by shims/src/jvs.c, which #includes it AFTER
 * its CONT_* / JVS_* defines (the tables reference them). Committed,
 * same rule as loader/menu_layout.h. */
#ifndef LAYOUTS_H
#define LAYOUTS_H

#define LAYOUT_PAD_TOURNAMENT 0
#define LAYOUT_PAD_OLD        1
#define LAYOUT_STICK          2
#define JVS_LAYOUT_N 6

typedef struct { unsigned dc, jvs; } jvs_map_t;

static const jvs_map_t JVS_LAYOUT_PAD[2][6] = {
  { {CONT_A, JVS_M}, {CONT_B, JVS_S}, {CONT_X, JVS_BARRAGE}, {CONT_Y, JVS_A}, {CONT_LTRIG, JVS_OD}, {CONT_RTRIG, JVS_A} },   /* TOURNAMENT */
  { {CONT_A, JVS_M}, {CONT_B, JVS_A}, {CONT_X, JVS_S}, {CONT_Y, JVS_BARRAGE}, {CONT_LTRIG, JVS_A}, {CONT_RTRIG, JVS_OD} },   /* OLD */
};

static const jvs_map_t JVS_LAYOUT_STICK[6] = {
  {CONT_A, JVS_A},
  {CONT_B, 0},
  {CONT_X, JVS_M},
  {CONT_Y, JVS_S},
  {CONT_Z, JVS_BARRAGE},
  {CONT_C, JVS_OD},
};

#endif /* LAYOUTS_H */
